// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lbbMult
arma::mat lbbMult(arma::mat x, arma::vec lpstart, arma::vec lpend, arma::mat lnn, arma::imat i2);
RcppExport SEXP _gamFactory_lbbMult(SEXP xSEXP, SEXP lpstartSEXP, SEXP lpendSEXP, SEXP lnnSEXP, SEXP i2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lpstart(lpstartSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lpend(lpendSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lnn(lnnSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type i2(i2SEXP);
    rcpp_result_gen = Rcpp::wrap(lbbMult(x, lpstart, lpend, lnn, i2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gamFactory_lbbMult", (DL_FUNC) &_gamFactory_lbbMult, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_gamFactory(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
