# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.expsmooth_cpp <- function(y, Xi, beta, x0, deriv) {
    .Call(`_gamFactory_expsmooth`, y, Xi, beta, x0, deriv)
}

.mgks_cpp <- function(y, dist, beta, deriv) {
    .Call(`_gamFactory_mgks`, y, dist, beta, deriv)
}

