#' Nested single-index effects constructor
#'
#' This function implements the nested single-index smooth of the form 
#' \eqn{s(\mathbf{x}_i^\top \boldsymbol{\alpha})}, where \eqn{\boldsymbol{\alpha}} 
#' is a vector of inner coefficients estimated jointly with the outer outer B-spline coefficients of \eqn{s(\cdot)}. 
#' The inner projection \eqn{z_i = \mathbf{x}_i^\top \boldsymbol{\alpha}} is first computed from the (mean-centered) 
#' covariate matrix, and then used as the argument of a B-spline basis expansion.
#'
#' @param object A \code{smooth.spec} object generated by \code{s_nest(..., trans = trans_linear())}, 
#'   within a \code{gam_nl} formula. The \code{xt} slot contains a named list
#'   \code{si} with the following optional elements:
#'   \itemize{
#'     \item \code{S}: custom penalty matrix of dimension \code{p x p} for
#'           \eqn{\boldsymbol{\alpha}}.
#'     \item \code{pord}: integer order of the P-splines difference penalty
#'           on \eqn{\boldsymbol{\alpha}}.
#'     \item \code{alpha}: numeric vector of length \code{p} giving initial
#'           values for \eqn{\boldsymbol{\alpha}}.
#'     \item \code{a0}: numeric vector of length \code{p} giving the offset
#'           \eqn{\boldsymbol{\alpha}_0}.
#'   }
#' @param data A list or data frame containing the model frame. The element
#'   named \code{object$term} must be a numeric matrix with \code{n} rows and
#'   \code{p} columns, as produced by \code{\link{data_si}}, where \code{n} is
#'   the number of observations and \code{p} is the number of single-index
#'   covariates.
#' @param knots An optional list of user-supplied knots for the outer B-spline
#'   basis construction. Can be \code{NULL} (default).
#'   
#' @details
#' The constructor proceeds through the following steps:
#' \itemize{
#'   \item \strong{Centering:} the covariate matrix \eqn{\mathbf{X}} is
#'         mean-centered column-wise. The column means are stored in
#'         \code{si$xm} for use during prediction on new data.
#'   \item \strong{Inner penalty:} three cases are supported, controlled via
#'         the \code{xt} argument passed to \code{s_nest()}:
#'         \itemize{
#'           \item No penalisation: when neither \code{si$S}
#'                 nor \code{si$pord} is supplied, \eqn{\boldsymbol{\alpha}} is
#'                 unpenalised.
#'           \item P-splines penalty: when \code{si$pord} is
#'                 supplied, a difference penalty of order \code{si$pord} is
#'                 constructed automatically.
#'           \item Custom penalty: when \code{si$S} is
#'                 supplied directly, it is used as the penalty matrix on
#'                 \eqn{\boldsymbol{\alpha}}.
#'         }
#'         In the first two cases, the penalty is diagonalised via an internal
#'         reparametrisation, and the rank is stored in \code{si$rank}.
#'   \item \strong{Initialisation:} initial values for \eqn{\boldsymbol{\alpha}} can be
#'         supplied via \code{alpha} (coefficients) and \code{a0} (offset),
#'         so that the full coefficient vector is
#'         \eqn{\boldsymbol{\alpha} = \boldsymbol{\alpha} + \boldsymbol{\alpha}_0}.
#'         If not supplied, defaults are chosen so that
#'         \eqn{\text{Var}(z_i) = 1} at initialisation.
#'   \item \strong{Outer smooth:} the projected index \eqn{z_i} is passed to
#'         an internal B-spline basis builder, which constructs the outer
#'         smooth design matrix and the corresponding smoothness penalty.
#'   \item \strong{Penalty assembly:} when an inner penalty is present, it is
#'         padded with zeros corresponding to the outer B-spline coefficients
#'         and appended as \code{out$S[[2]]}.
#' }
#'
#' @return A smooth object of class \code{c("si", "nested")} containing:
#'   \itemize{
#'     \item \code{X}: the outer B-spline design matrix evaluated at the
#'           projected index \eqn{z_i = \mathbf{x}_i^\top \boldsymbol{\alpha}}.
#'     \item \code{S}: a list of penalty matrices. \code{S[[1]]} is the outer
#'           smoothness penalty; \code{S[[2]]} is the (padded) inner penalty
#'           on \eqn{\boldsymbol{\alpha}}, present only when penalisation is requested.
#'     \item \code{xt$si}: the updated \code{si} list, including stored column
#'           means \code{si$xm}, reparametrised design matrix \code{si$X},
#'           reparametrisation matrix \code{si$B}, initialised coefficients
#'           \code{si$alpha} and \code{si$a0}, and penalty rank \code{si$rank}.
#'     \item All further slots required by the \pkg{mgcv} fitting engine
#'           (\code{bs.dim}, \code{rank}, \code{null.space.dim}, etc.).
#'   }
#'
#' @examples
#' ### Single-index smooth: s(x1 * a1 + x2 * a2 + x3 * a3)
#' library(mgcViz)
#' set.seed(123)
#' n <- 1000; p <- 3; b <- 1:p
#' X   <- matrix(rnorm(n * p), nrow = n)
#' X <- X - matrix(colMeans(X), nrow = n, ncol = p, byrow = TRUE) # center
#' Xb  <- X %*% b
#' y   <- 2 * sin(Xb) + rnorm(n)
#' dat <- data.frame(y = y)
#' dat$X <- data_linear(X, cnames = paste0("x.", 1:p))
#' 
#' ### No inner penalty (case a)
#' fit <- gam_nl(list(y ~ s_nest(X, trans = trans_linear()), ~1), data = dat)
#' get_alpha(fit$smooth[[1]]) # estimated single-index coefficients in the var(alpha)=1 space
#' b/sqrt(sum(b^2)) # true single-index coefficients in the var=1 space
#' print(plot(getViz(fit)), pages=1)
#' print(plot(getViz(fit), inner=TRUE), pages=1)
#' 
#' ### P-splines penalty on a of order 1 (case b)
#' fit <- gam_nl(list(y ~ s_nest(X, trans = trans_linear(pord=1)), ~1),
#'               data = dat)
#' get_alpha(fit$smooth[[1]]) # estimated single-index coefficients in the var(alpha)=1 space
#' b/sqrt(sum(b^2)) # true single-index coefficients in the var=1 space
#' print(plot(getViz(fit)), pages=1)
#' print(plot(getViz(fit), inner=TRUE), pages=1)
#' 
#' ### Custom penalty on a (case c)
#' S   <- diag(p)
#' fit <- gam_nl(list(y ~ s_nest(X, trans = trans_linear(S=S)), ~1),
#'               data = dat)
#' get_alpha(fit$smooth[[1]]) # estimated single-index coefficients in the var(alpha)=1 space
#' b/sqrt(sum(b^2)) # true single-index coefficients in the var=1 space
#' print(plot(getViz(fit)), pages=1)
#' print(plot(getViz(fit), inner=TRUE), pages=1)
#' 
#' @seealso \code{\link{data_linear}}, \code{\link{trans_linear}}, \code{\link{s_nest}}
#'
#' @name smooth.construct.si.smooth.spec
#' @rdname smooth.construct.si.smooth.spec
#' @importFrom Matrix rankMatrix
#' @export
smooth.construct.si.smooth.spec <- function(object, data, knots){
  
  # Most information on single index matrix and penalty is inside "si" list.
  si <- object$xt$si
  if( is.null(si) ){ si <- object$xt$si <- list() }
  
  # Inner model matrix (to be projected via single index)
  Xi <- data[[object$term]]
  
  # Need to center Xi and save colMeans because we need to subtract it when predicting using new data
  Xi <- scale(Xi, scale = FALSE)
  si$xm <- attr(Xi, "scaled:center")
  
  di <- ncol( Xi )
  n <- nrow( Xi )
  
  # Dealing with inner penalty
  Si <- si$S
  no_pen <- is.null(Si) && is.null(si$pord)
  if( no_pen ){ # Case [a] no penalisation
    si$X <- Xi
    si$B <- diag(nrow = ncol(Xi))
    si$rank <- 0 
  } else {
    if( is.null(Si) ){ # Case [b] "P-splines" penalty
      Si <- .psp(d = di, ord = si$pord)
      rankSi <- ncol(Xi) - si$pord
    } else { # Case [c] custom penalty Si
      rankSi <- rankMatrix(Si)
    }
    # Reparametrise Xi so that the penalty on the single index vector is diagonal
    si <- append(si, gamFactory:::.diagPen(X = Xi, S = Si, r = rankSi))
  }
  
  # alpha is vector of inner coefficients, si$alpha is a vector of initial values for it.
  # alpha0 is an offset such that the full_alpha = alpha + alpha0
  if( is.null(si$a0) ){
    if( no_pen ){
      si$a0 <- rep(0, di)
    } else {
      si$a0 <- rep(1, di)
    }
  }
  if( is.null(si$alpha) ){ 
    if( is.null(si$a0) || all(si$a0 == 0) ){
      si$alpha <- rep(1, di) 
    } else {
      si$alpha <- rep(0, di) 
    }
  }
  # Reparametrise and then impose that variance should be 1
  si$alpha <- solve(si$B, si$alpha)
  si$a0 <- solve(si$B, si$a0)
  tmp <- sd(si$X %*% (si$alpha + si$a0))
  si$alpha <- si$alpha / tmp
  si$a0 <- si$a0 / tmp
  
  # Compute single index vector and store it in the data
  ax <- drop( si$X %*% (si$alpha + si$a0) ) 
  data[[object$term]] <- ax
  
  # Construct the B-splines corresponding to the outer smooth effect 
  out <- .build_nested_bspline_basis(object = object, data = data, knots = knots, si = si)
  
  # Add inner penalty matrix (diagonalised and padded with zeros corresponding to the outer coefficients)
  if( !no_pen ){
    dsmo <- out$bs.dim - di
    si <- out$xt$si
    out$S[[2]] <- rbind(cbind(si$S, matrix(0, di, dsmo)),
                        cbind(matrix(0, dsmo, di), matrix(0, dsmo, dsmo)))
    out$null.space.dim <- out$null.space.dim + (out$bs.dim - si$rank)
    out$rank <- c(out$rank, si$rank)
  }
  
  class(out) <- c("si", "nested")
  return( out )
} 
