#' Nested single-index and adaptive exponential smoothing constructor
#'
#' @description
#' This function implements a double-nested smooth of the form
#' \eqn{f_t = s(\text{expsmooth}(z_t, \omega_t))}, which combines an inner linear 
#' projection (single-index transformation) with a middle adaptive exponential 
#' smoothing layer, followed by an outer B-spline basis expansion. 
#' The inner coefficients \eqn{\boldsymbol{\alpha}_{si}} and the smoothing weight 
#' coefficients \eqn{\boldsymbol{\alpha}_{nexp}} are estimated jointly with the 
#' outer B-spline coefficients of \eqn{s(\cdot)}.
#'
#' @param object A \code{smooth.spec} object generated by 
#'   \code{s_nest(..., trans = trans_linear_nexpsm())}, within a \code{gam_nl} formula. 
#'   The \code{xt} slot contains a named list \code{trans} with the following elements:
#'   \itemize{
#'     \item \code{n_si}: integer specifying the number of single-index covariates 
#'           (the remaining columns are used for the exponential smoothing weights).
#'     \item \code{S_si}, \code{S_nexp}: optional custom penalty matrices for 
#'           \eqn{\boldsymbol{\alpha}_{si}} and \eqn{\boldsymbol{\alpha}_{nexp}}.
#'     \item \code{pord}: integer order of the P-splines difference penalty 
#'           (applied to \eqn{\boldsymbol{\alpha}_{si}} and/or \eqn{\boldsymbol{\alpha}_{nexp}}).
#'     \item \code{alpha_si}, \code{alpha_nexp}: numeric vectors giving initial 
#'           values for the respective coefficients.
#'     \item \code{alpha_center}: numeric vectors giving the offset 
#'           values. \code{alpha_center} is applied to the single-index coefficients.
#'   }
#' @param data A list or data frame containing the model frame. The element
#'   named \code{object$term} must be a combined numeric matrix \code{xw} with 
#'   \code{n} rows, where the first \code{n_si} columns form \eqn{X_{si}} and 
#'   the remaining columns form \eqn{X_{nexp}}.
#' @param knots An optional list of user-supplied knots for the outer B-spline
#'   basis construction. Can be \code{NULL} (default).
#'  
#' @details
#' The constructor builds the nested smooth through the following steps:
#' \itemize{
#'   \item \strong{Covariate Partitioning & Centering:} The input matrix is split into 
#'         \eqn{X_{si}} and \eqn{X_{nexp}} based on \code{n_si}. Both matrices are 
#'         mean-centered column-wise. Column means are stored in \code{xt$trans$xm_si} 
#'         and \code{xt$trans$xm_nexp} for prediction.
#'   \item \strong{Inner Penalties:} Penalisation for both parameter spaces is handled 
#'         independently. If \code{pord} or custom matrices (\code{S_si}, \code{S_nexp}) 
#'         are supplied, difference or custom penalties are constructed and diagonalised 
#'         via internal reparametrisation. The respective ranks are stored.
#'   \item \strong{Initialisation:} Initial values for \eqn{\boldsymbol{\alpha}_{si}} 
#'         and \eqn{\boldsymbol{\alpha}_{nexp}} are configured. The single-index offset 
#'         is applied such that the full coefficient vector becomes 
#'         \eqn{\boldsymbol{\alpha}_{si} = \boldsymbol{\alpha}_{si} + \boldsymbol{\alpha}_{center}}.
#'         If not supplied by the user, defaults are chosen to ensure 
#'         \eqn{\text{Var}(z_t) \approx 1} at initialisation and stable starting 
#'         smoothing weights.
#'   \item \strong{Dynamic Transformation:} The sequential layers are computed:
#'         \itemize{
#'           \item \emph{Single-index:} \eqn{z_t = \mathbf{x}_{si,t}^\top \boldsymbol{\alpha}_{si}}
#'           \item \emph{Adaptive weights:} \eqn{\omega_t = \text{sigmoid}(\mathbf{x}_{nexp,t}^\top \boldsymbol{\alpha}_{nexp})}
#'           \item \emph{Exponential smoothing:} \eqn{s_t = \omega_t s_{t-1} + (1 - \omega_t) z_t}
#'         }
#'   \item \strong{Outer Smooth:} The smoothed sequence \eqn{s_t} is passed to an internal 
#'         B-spline builder to construct the outer design matrix and smoothness penalty.
#'   \item \strong{Penalty Assembly:} The outer B-spline penalty and the inner penalties 
#'         (for \eqn{\boldsymbol{\alpha}_{si}} and \eqn{\boldsymbol{\alpha}_{nexp}}) are 
#'         padded with zeros to match the total parameter dimension and appended into 
#'         the \code{S} list using block-diagonal structures.
#' }
#'
#' @return A smooth object of class \code{c("si_nexpsm", "nested")} containing:
#'   \itemize{
#'     \item \code{X}: the outer B-spline design matrix evaluated at the 
#'           dynamically smoothed index \eqn{s_t}.
#'     \item \code{S}: a list of penalty matrices. \code{S[[1]]} is the outer 
#'           smoothness penalty; \code{S[[2]]} and \code{S[[3]]} (if requested) are 
#'           the padded inner penalties for \eqn{\boldsymbol{\alpha}_{si}} and 
#'           \eqn{\boldsymbol{\alpha}_{nexp}}.
#'     \item \code{xt$trans}: the updated transformation list, containing stored column 
#'           means, reparametrised design matrices, and initialised coefficients 
#'           (including \code{alpha_center}).
#'     \item All further slots required by the \pkg{mgcv} fitting engine 
#'           (\code{bs.dim}, \code{rank}, \code{null.space.dim}, etc.).
#'   }
#'
#' @examples
#' #### Example for dual-nested effect
#' library(mgcViz)
#' set.seed(123)
#' n <- 1000; p <- 3; b_si <- 1:p; b_nexp <- 1:3
#' 
#' tim <- seq(0, 2*pi, length.out = n)
#' temp <- sin(tim) + rnorm(n, 0, 0.5)
#' w <- cbind(1, tim, tim^2)
#' w[,-1] <- scale(w[,-1], scale=FALSE)
#' x <- matrix(runif(p * n), ncol = p)
#' xw <- cbind(x, w)
#' colnames(xw) <- c("x1","x2","x3","w1","w2","w3")
#' 
#' # Generate response based on the true derivative structure
#' y <- gamFactory:::deriv_si_nexp(X_si = x, X_nexp = w, param = c(b_si,b_nexp))$d0 + rnorm(n)
#' dat <- data.frame(y = y, xw = I(xw))
#' 
#' ### Base fit without inner penalties
#' fit <- gam_nl(list(y ~ s_nest(xw, trans = trans_linear_nexpsm(n_si = 3), k = 10, m = c(4,2)), ~1),
#'               data = dat, family = fam_gaussian(), control=list(trace=TRUE))
#' 
#' get_alpha(fit$smooth[[1]]) # estimated coefficients
#' b_si/sqrt(sum(b_si^2))     # true single-index coefficients in the var=1 space
#' print(plot(getViz(fit)), pages=1)
#' print(plot(getViz(fit), inner=TRUE), pages=1)
#' 
#' ### P-splines penalty on order 1
#' fit_p <- gam_nl(list(y ~ s_nest(xw, trans = trans_linear_nexpsm(n_si = 3, pord=1)), ~1),
#'                 data = dat)
#' get_alpha(fit_p$smooth[[1]])
#' b_si/sqrt(sum(b_si^2))
#' print(plot(getViz(fit_p)), pages=1)
#' print(plot(getViz(fit_p), inner=TRUE), pages=1)
#' 
#' ### Custom penalty on alpha_si
#' S_si   <- diag(p)
#' fit_s <- gam_nl(list(y ~ s_nest(xw, trans = trans_linear_nexpsm(n_si = 3, S_si = S_si)), ~1),
#'                 data = dat)
#' get_alpha(fit_s$smooth[[1]])
#' b_si/sqrt(sum(b_si^2))
#' print(plot(getViz(fit_s)), pages=1)
#' print(plot(getViz(fit_s), inner=TRUE), pages=1)
#' 
#' @seealso \code{\link{data_linear_nexpsm}}, \code{\link{trans_linear_nexpsm}}, \code{\link{s_nest}}
#' 
#' @name smooth.construct.si_nexpsm.smooth.spec
#' @rdname smooth.construct.si_nexpsm.smooth.spec
#' @importFrom Matrix rankMatrix bdiag
#' @export

smooth.construct.si_nexpsm.smooth.spec <- function(object, data, knots){
  si <- object$xt$si
  if(is.null(si)) si <- object$xt$si <- list()
  positive_si <- isTRUE(si$positive_si)
  
  ## --- Phase 0 & 1: Data Partitioning and Centering ---
  # 0. Data Partitioning
  Xall <- data[[object$term]] # Xall = [X_si | X_nexp | times]
  nms  <- colnames(Xall)
  i_t  <- which(nms == "times")            
  times <- NULL                           
  if (length(i_t)) {
    times <- Xall[ , i_t]
    Xall  <- Xall[ , -i_t, drop = FALSE]
  }
  si$times <- times
  all_columns <- ncol(Xall) # Xall = [X_si | X_nexp]
  
  # For messy(flatten) data
  if(length(i_t)){
    n_si <- si$n_si
    n_nexp <- si$n_nexp
    if (is.null(n_si)) {
      stop("`n_si` is NULL: the number of single-index covariates must be specified.", call. = FALSE)
    }
    if (is.null(n_nexp)) {
      stop("`n_nexp` is NULL: the number of exponential-smoothing covariates must be specified.", call. = FALSE)
    }
    
    all_columns_true <- n_si + n_nexp
    nrep <- ceiling(all_columns / all_columns_true) # nrep: umber of repeats
    n_obs  <- nrow(Xall)
    stopifnot(ncol(Xall) == nrep * (n_si + n_nexp))
    
    X_block <- Xall[, 1:(nrep * n_si), drop = FALSE]
    W_block <- Xall[, (nrep * n_si + 1):(nrep * (n_si + n_nexp)), drop = FALSE]
    X_si_long   <- matrix(NA_real_, nrow = n_obs * nrep, ncol = n_si)
    X_nexp_long <- matrix(NA_real_, nrow = n_obs * nrep, ncol = n_nexp)
    
    for (d in 1:n_obs) {
      for (s in 1:nrep) {
        row <- (d - 1) * nrep + s
        X_si_long[row, ]   <- X_block[d, ((s - 1) * n_si + 1):(s * n_si)]
        X_nexp_long[row, ] <- W_block[d, ((s - 1) * n_nexp + 1):(s * n_nexp)]
      }
    }
    
    # names（eg. c("East","South","West","North")、c("intercept","time_diff")）
    colnames(X_si_long)   <- paste0("x", 1:n_si)      # c("East","South","West","North")
    colnames(X_nexp_long) <- paste0("w", 1:n_nexp)    # c("intercept","time_diff")
    X_si   <- X_si_long
    X_nexp <- X_nexp_long
    ok_si   <- rowSums(is.finite(X_si))   == ncol(X_si)
    ok_nexp <- rowSums(is.finite(X_nexp)) == ncol(X_nexp) # drop INF rows
    last_good <- max(which(ok_si & ok_nexp))
    
    X_si   <- X_si[  1:last_good, , drop = FALSE]
    X_nexp <- X_nexp[1:last_good, , drop = FALSE]
    si$n_si <- n_si
    si$n_nexp <- n_nexp
    
  }else{
    # For normal data
    if (!is.null(si$n_nexp)){
      n_si <- all_columns - si$n_nexp
      n_nexp <- si$n_nexp
    } else{
      n_nexp <- all_columns - si$n_si
      n_si <- si$n_si
    }
    if (n_si + n_nexp != all_columns) {
      stop(sprintf("Inconsistent number of variables: n_si + n_nexp = %d + %d != %d (ncol of Xall)", n_si, n_nexp, all_columns))
    }
    
    si$n_si <- n_si
    si$n_nexp <- n_nexp
    X_si <- Xall[, 1:n_si,       drop = FALSE]
    X_nexp <- Xall[, (n_si+1):(n_si+n_nexp), drop = FALSE]
  }
  
  # 1. center X_si (optionally)
  if (isTRUE(si$center)){
    X_si <- scale(X_si, scale = FALSE)
    si$xm <- attr(X_si, "scaled:center")
  } else {
    si$xm <- rep(0, n_si)
  }

  ## --- Phase 2: Single-Index: Initialization ---
  S_si <- si$S_si
  noPen_si <- is.null(S_si) && is.null(si$pord)
  
  # Diagonalise S_si by .diagPen (3 cases)
  if (noPen_si){  # Case [a] no penalisation
    si$X_si    <- X_si
    si$B_si    <- diag(n_si)
    si$rank_si <- 0
  } else {
    if (is.null(S_si)){  # Case [b] "P-splines" penalty
      S_si  <- .psp(d = n_si, ord = si$pord)
      rank_si <- n_si - si$pord
    } else {  # Case [c] custom penalty Si
      rank_si <- Matrix::rankMatrix(S_si)
    }
    diag_pen_si <- gamFactory:::.diagPen(X = X_si, S = S_si, r = rank_si)
    si$S_si   <- diag_pen_si$S
    si$rank_si <- diag_pen_si$rank
    si$B_si    <- diag_pen_si$B
    si$X_si    <- diag_pen_si$X
  }
  
  # Initialise alpha_si and alpha_center
  if( is.null(si$alpha_center) ){
    if( noPen_si ){
      si$alpha_center <- rep(0, n_si)
    } else {
      si$alpha_center <- rep(1, n_si)
    }
  }
  if( is.null(si$alpha_si) ){ 
    if( is.null(si$alpha_center) || all(si$alpha_center == 0) ){
      si$alpha_si <- rep(1, n_si) 
    } else {
      si$alpha_si <- if (positive_si) rep(0.01, n_si) else rep(0, n_si)
    }
  }
  
  # Reparametrise by B & Imposed variance of `z` to 1(by `tmp`)
  si$alpha_si  <- solve(si$B_si, si$alpha_si)
  si$alpha_center <- solve(si$B_si, si$alpha_center)
  
  ## maybe we don't need to Imposed variance of `z` to 1(by `tmp`) here
  ## because this will be done with s
  # tmp <- sd(si$X_si %*% (si$alpha_si + si$alpha_center))
  # si$alpha_si      <- si$alpha_si / tmp
  # si$alpha_center  <- si$alpha_center / tmp
  
  if (positive_si) {
    # transform to log scale to ensure positive
    si$alpha_si <- log(pmax(si$alpha_si, 1e-8))
  }
  
  ## --- Phase 3: Exponential Smoothing: Initialization ---
  S_nexp <- si$S_nexp
  noPen_nexp <- is.null(S_nexp)
  
  #Diagonalise S_nexp by .diagPen (2 cases)
  if (noPen_nexp){
    si$X_nexp     <- X_nexp
    si$B_nexp     <- diag(n_nexp)
    si$rank_nexp <- 0
  } else {
    rAlp_nexp <- Matrix::rankMatrix(S_nexp)
    diag_pen_nexp <- gamFactory:::.diagPen(X = X_nexp, S = S_nexp, r = rAlp_nexp)
    si$S_nexp     <- diag_pen_nexp$S
    si$rank_nexp <- diag_pen_nexp$rank
    si$B_nexp     <- diag_pen_nexp$B
    si$X_nexp     <- diag_pen_nexp$X
  }
 
  # Initialise alpha_nexp -> Reparametrise by B -> Calculate g by deriv_si_nexp
  if (is.null(si$alpha_nexp)){
    si$alpha_nexp <- rep(0,n_nexp)
    g <- deriv_si_nexp(X_si = si$X_si, 
                       X_nexp = si$X_nexp, 
                       param = c(si$alpha_nexp,si$alpha_si),
                       times = times, 
                       alpha_center = si$alpha_center,
                       Z0 = si$Z0,
                       positive_si = positive_si)$d0
  } else {
    alpha_nexp <- solve(si$B_nexp) %*% si$alpha_nexp
    si$alpha_nexp <- alpha_nexp
    g <- deriv_si_nexp(X_si = si$X_si, 
                       X_nexp = si$X_nexp, 
                       param = c(si$alpha_nexp,si$alpha_si),
                       times = times, 
                       alpha_center = si$alpha_center,
                       Z0 = si$Z0,
                       positive_si = positive_si)$d0
  }
  
  ## --- Phase 4: Global: Standardization ---
  # Imposed variance of s to 1(by sd(g))
  # alpha_si_inner has different scales
  if (positive_si) {
    si$alpha_si <- si$alpha_si - log(sd(g)) 
  } else {
    si$alpha_si <- si$alpha_si / sd(g)      
  }
  si$alpha_center <- si$alpha_center / sd(g) 
  
  # center and scale s
  s <- (g - mean(g))/sd(g)
  data[[object$term]] <- s

  ## --- Phase 5 & 6: Outer B-Spline Construction and Global Penalty Assembly ---
  # 5. Outer B-Spline Construction
  si$alpha <- c(si$alpha_nexp, si$alpha_si)  # .build_nested_bspline_basis will use si$alpha directly
  out <- gamFactory:::.build_nested_bspline_basis(object = object,
                                                  data   = data,
                                                  knots  = knots,
                                                  si     = si)
  
  # 6. Global Penalty Assembly
  # alpha_si penalty
  if (!noPen_si) {
    
    di_si <- ncol(si$X_si)
    di_nexp <- ncol(si$X_nexp)
    di_beta <- out$bs.dim - di_si - di_nexp
    
    si   <- out$xt$si
    S_si <- si$S_si
    S_nexp <- matrix(0, di_nexp, di_nexp)
    S_beta <- matrix(0, di_beta, di_beta)
    
    out$S[[2]] <- as.matrix(Matrix::bdiag(S_nexp, S_si, S_beta))
    out$null.space.dim <- out$null.space.dim + (out$bs.dim - si$rank_si)
    out$rank <- c(out$rank, si$rank_si)
  }
  
  # alpha_nexp penalty
  if (!noPen_nexp) {
    
    di_si <- ncol(si$X_si)
    di_nexp <- ncol(si$X_nexp)
    di_beta <- out$bs.dim - di_si - di_nexp
    
    S_nexp <- si$S_nexp
    S_beta <- matrix(0, di_beta, di_beta)
    S_si <- matrix(0, di_si, di_si)
    
    out$S[[3]] <- as.matrix(Matrix::bdiag(S_nexp, S_si, S_beta))
    out$null.space.dim <- out$null.space.dim + (out$bs.dim - si$rank_nexp)
    out$rank <- c(out$rank, si$rank_nexp)
  }
  
  S2 <- if (!is.null(out$S) && length(out$S) >= 2) out$S[[2]] else NULL
  S3 <- if (!is.null(out$S) && length(out$S) >= 3) out$S[[3]] else NULL
  
  if (is.null(S2) && !is.null(S3)) {
    out$S[[2]] <- out$S[[3]]
    out$S[[3]] <- NULL
  }
  
  ## --- Return ---
  class(out) <- c("si_nexpsm", "nested")
  return(out)
}
