#' Nested adaptive exponential smoothing smooth constructor
#'
#' Constructs a nested smooth term of type \code{"nexpsm"}, which estimates an
#' adaptive exponential smoothing model of the form
#' \deqn{\tilde{s}_i = \omega_i \tilde{s}_{i-1} + (1 - \omega_i) x_i, \qquad i \geq 1,}
#' with \eqn{\tilde{s}_0 = x_0} and \eqn{\omega_i = \phi(\tilde{\mathbf{x}}_i^\top \mathbf{a})},
#' where \eqn{\phi} is the logistic function and \eqn{\tilde{\mathbf{x}}_i} is a vector of
#' covariates driving the smoothing rate. The smoothed series \eqn{\tilde{s}_i} is then
#' used as the argument of an outer B-spline basis expansion \eqn{s(\tilde{s}_i)}.
#' This type of transformation allows for different time granularities in the inner exponential and outer smooths. 
#' It is particularly useful for handling data structures where the response variable is observed at a 
#' different frequency than the covariates driving the smoothing rate (e.g., daily response with hourly covariates).
#'
#' @details
#' The constructor proceeds through the following steps:
#' \itemize{
#'   \item \strong{Data extraction:} the input matrix \code{data[[object$term]]},
#'         as produced by \code{\link{data_nexpsm}}, is unpacked into:
#'         \itemize{
#'           \item \code{"y"} columns: the scalar series \eqn{x_i} to be smoothed,
#'                 stored as a flat vector of length \code{n * nrep}.
#'           \item \code{"x"} columns: the model matrix \eqn{\tilde{\mathbf{X}}} for
#'                 the smoothing rate, with \code{nrep} blocks of \code{dXi} columns
#'                 tiled row-wise into an \code{(n * nrep) x dXi} matrix.
#'           \item \code{"times"} column (optional): observation times of the GAM
#'                 response, passed to \code{expsmooth()} to handle more frequent observations 
#'                 in the covariate compared to the response. For instance, 
#'                 if covariates are observed every unit of time (1,2,...,10) and response is observed every 2 units of time 
#'                 (2,4,6,8,10), then \code{times} should be \code{c(2,4,6,8,10)} to indicate that the response is observed at those time points.
#'                 If not present, \code{expsmooth()} is called with \code{times = NULL} and assumes equally spaced observations.
#'          }
#'   \item \strong{Inner penalty:} two cases are supported via \code{si$S}:
#'         \itemize{
#'           \item \strong{No penalty} (\code{si$S = NULL}): \eqn{\mathbf{a}} is
#'                 unpenalised; the identity reparametrisation is used.
#'           \item \strong{Custom penalty} (\code{si$S} supplied): the model matrix
#'                 \eqn{\tilde{\mathbf{X}}} is reparametrised via \code{.diagPen} so
#'                 that the penalty on \eqn{\mathbf{a}} is diagonal.
#'         }
#'   \item \strong{Initialisation:} the inner coefficient vector
#'         \eqn{\boldsymbol{\alpha} = (\alpha_0, \mathbf{a}^\top)^\top} is initialised
#'         as follows. If \code{si$alpha} is \code{NULL}, \eqn{\mathbf{a}} is set to
#'         \eqn{\mathbf{0}} and \eqn{\alpha_0 = \log(1 / \text{sd}(\tilde{s}))} is
#'         chosen so that \eqn{\text{sd}(\tilde{s}_i) = 1} at initialisation.
#'         If \code{si$alpha} is supplied, it is reparametrised via \code{si$B} and
#'         \eqn{\alpha_0} is recalculated accordingly. Note that \eqn{\alpha_0} is
#'         a global scaling parameter and is \strong{never penalised}.
#'   \item \strong{Outer smooth:} the centered and scaled series
#'         \eqn{e^{\alpha_0}(\tilde{s}_i - \bar{\tilde{s}})} is passed to an internal
#'         B-spline basis builder to construct the outer smooth design matrix and
#'         smoothness penalty.
#'   \item \strong{Penalty assembly:} when an inner penalty is present, it is embedded
#'         in a larger matrix of dimension \code{bs.dim x bs.dim} as
#'         \eqn{\text{blockdiag}(0, \mathbf{S}, \mathbf{0})}, where the leading
#'         \eqn{0} leaves \eqn{\alpha_0} unpenalised and the trailing \eqn{\mathbf{0}}
#'         block corresponds to the outer B-spline coefficients.
#' }
#'
#' @param object A \code{smooth.spec} object generated by \code{s_nest(..., bs = "nexpsm")}
#'   within a \code{gam_nl} formula. The \code{xt} slot may contain a named list
#'   \code{si} with the following optional elements:
#'   \itemize{
#'     \item \code{S}: custom penalty matrix of dimension \code{dXi x dXi} for the
#'           smoothing rate coefficients \eqn{\mathbf{a}}. If \code{NULL} (default),
#'           \eqn{\mathbf{a}} is unpenalised.
#'     \item \code{alpha}: numeric vector of length \code{dXi} giving initial values
#'           for \eqn{\mathbf{a}}. If \code{NULL} (default), initialised to
#'           \eqn{\mathbf{0}}.
#'   }
#' @param data A list or data frame containing the model frame. The element named
#'   \code{object$term} must be a numeric matrix as produced by
#'   \code{\link{data_nexpsm}}, with columns named \code{"y"}, \code{"x"}, and
#'   optionally \code{"times"}.
#' @param knots An optional list of user-supplied knots for the outer B-spline basis
#'   construction. Can be \code{NULL} (default).
#'
#' @return A smooth object of class \code{c("nexpsm", "nested")} containing:
#'   \itemize{
#'     \item \code{X}: the outer B-spline design matrix evaluated at the centered and
#'           scaled smoothed series \eqn{e^{\alpha_0}(\tilde{s}_i - \bar{\tilde{s}})}.
#'     \item \code{S}: a list of penalty matrices. \code{S[[1]]} is the outer
#'           smoothness penalty on the B-spline coefficients; \code{S[[2]]} is the
#'           block-embedded inner penalty on \eqn{\boldsymbol{\alpha}}, present only
#'           when \code{si$S} is supplied.
#'     \item \code{xt$si}: the updated \code{si} list, including the reparametrised
#'           model matrix \code{si$X}, reparametrisation matrix \code{si$B},
#'           initialised coefficients \code{si$alpha}, stored series \code{si$x},
#'           observation times \code{si$times}, and penalty rank \code{si$rank}.
#'     \item All further slots required by the \pkg{mgcv} fitting engine
#'           (\code{bs.dim}, \code{rank}, \code{null.space.dim}, etc.).
#'   }
#'
#' @examples
#' n <- 1000
#' set.seed(123)
#'
#' ### True underlying series and response
#' xseq <- seq(-4, 4, length.out = n)
#' x_true <- sin(xseq)                           # series to be smoothed
#' y <- x_true * cos(x_true / 2) + rnorm(n, 0, 0.5)
#'
#' ### Model matrix for the smoothing rate: intercept + quadratic trend
#' Xi <- cbind(1, xseq, xseq^2)
#'
#' ### Prepare data matrix for nexpsm:
#' ### y is the series to smooth, Xi drives the time-varying smoothing rate
#' dat <- data.frame(y = y)
#' dat$Xsm <- data_nexpsm(y = x_true, X = Xi)
#'
#' ### Fit via smoothCon
#' aaa <- smoothCon(s_nest(Xsm, trans = trans_nexpsm(), m = c(4, 2)), data = dat)
#' 
#' @seealso \code{\link{data_nexpsm}},
#'   \code{\link{smooth.construct.si.smooth.spec}},
#'   \code{\link{smooth.construct.mgks.smooth.spec}},
#'   \code{\link{smooth.construct.si_nexpsm.smooth.spec}}
#'
#' @name smooth.construct.nexpsm.smooth.spec
#' @rdname smooth.construct.nexpsm.smooth.spec
#' @importFrom Matrix rankMatrix
#' @export
smooth.construct.nexpsm.smooth.spec <- function(object, data, knots)
{ 
  si <- object$xt$si
  if( is.null(si) ){ si <- object$xt$si <- list() }
  
  # Extract variables from data frame:
  # - "y" is variable to be exponentially smoothed (stored in vector or matrix)
  # - "x" is model matrix used to model the exp smoothing rate
  # - "times" is the vector of times that at which the response variable of the 
  #           GAM is observed (hence not the same at the GAM above). 
  Xi <- data[[object$term]]
  n <- nrow( Xi )
  nms <- colnames(Xi)
  x <- as.vector( t(Xi[ , which(nms == "y")]) )
  times <- NULL
  tmp <- which(nms == "times")
  if( length(tmp) ){
    times <- Xi[ , tmp]
  }
  Xi <- Xi[ , which(nms == "x"), drop = FALSE]
  nrep <- ceiling( length(x)/n )
  dXi <- ncol(Xi)/nrep
  if(nrep > 1){
    tmp <- rep(1:dXi, nrep)
    Xi <- apply(Xi, 1, function(x) do.call("cbind", tapply(x, tmp, I)), simplify = FALSE)
    Xi <- do.call("rbind", Xi)
  }
  Si <- si$S
  di <- ncol(Xi) + 1 # + 1 because we have extra scaling parameter multiplying output of the exp smooth.
  # Note that this extra parameter should NOT be penalised by Si
  
  if( !is.null(Si) ){ # Reparametrise Xi so that the penalty on alpha is diagonal
    si <- append(si, gamFactory:::.diagPen(X = Xi, S = Si, r = rankMatrix(Si)))
  } else { # No inner penalty 
    si$X <- Xi
    si$B <- diag(nrow = ncol(Xi))
    si$rank <- 0 
  }
  
  # Need to initialize inner coefficients?
  alpha <- si$alpha
  if( is.null(alpha) ){ 
    # alpha[1] s.t. sd(inner_lin_pred) = 1 (target variance)
    g <- expsmooth(y = x, Xi = si$X, beta = rep(0, di-1), times = times)$d0
    alpha <- si$alpha <- c(log(1/sd(g)), rep(0, di-1))
  } else {
    alpha <- solve(si$B) %*% alpha
    g <- expsmooth(y = x, Xi = si$X, beta = alpha, times = times)$d0
    alpha <- si$alpha <- c(log(1/sd(g)), alpha)
  }
  
  # Center and scale the initialized inner linear predictor
  data[[object$term]] <- exp(alpha[1]) * (g - mean(g))
  
  si$x <- x
  si$times <- times
  
  out <- .build_nested_bspline_basis(object = object, data = data, knots = knots, si = si)
  
  # Add inner penalty matrix: rbind(0, cbind(0, si$S) makes so first element of alpha (inner parameters)
  # is unpenalised (this is the scaling parameter)
  if( !is.null(Si) ){
    dsmo <- out$bs.dim - di
    si <- out$xt$si
    out$S[[2]] <- rbind(cbind(rbind(0, cbind(0, si$S)), matrix(0, di, dsmo)),
                        cbind(matrix(0, dsmo, di), matrix(0, dsmo, dsmo)))
    out$null.space.dim <- out$null.space.dim + (out$bs.dim - si$rank)
    out$rank <- c(out$rank, si$rank)
  }
  
  class(out) <- c("nexpsm", "nested")
  return( out )
} 
